services:
  api:
    container_name: evolution_audio_converter
    image: atendai/evolution-audio-converter:latest
    restart: always
    ports:
      - 4040:4040
    networks:
      - evolution-net
    environment:
      - PORT=4040
      - API_KEY=${API_KEY:-429683C4C977415CAAFCCE10F7D57E11}
      
    expose:
      - 4040


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
